### ISSUE TITLE
Searching on any text

### ISSUE THREAD

**Issue by Jorieke** [GIScience/ohsome-now-stats-frontend#111]
Hello, 

The ohsome now stats seem to work at the moment only if there are hashtags used in a changeset comment. In https://resultmaps.neis-one.org/osm-changesets#2/34.0/1.4 it is possible to search on any text in the changeset comment, would that be a possibility to add as well in your dashboard? 

Why I am asking this is because we recently did mapping in Mayotte, but there was no specific hashtag used, only just the description in the changeset comment Mayotte. And I am thus currently not able to properly review what has been done.

**Comment by ElJocho** [comment]
Hey Jorieke, 

sorry for the late reply, it seems we simply overlooked the request. 
Unfortunately it is neither possible nor planned to be able to filter by any text in the changeset comment, since our backend is not build to support this kind of query.

If its just for a one of analysis of the project feel free to reach out to the ohsome team, then we can see what we can do :)

**Comment by Jorieke** [comment]
Thanks for the reply and update Jochen, I will reach out to you separately, thanks for the offer!
