### ISSUE TITLE
Filtering for the length of the campaign

### ISSUE THREAD

**Issue by pedrito1414** [GIScience/ohsome-now-stats-frontend#112]
Hey all, I use ohsome all the time to track progress, communicate contributions and acknowledge mappers' efforts. I mostly use it for specific campaigns such as #KnowYourCity or #2024nigeriafloods and am usually looking for contriutor / contributions stats over the lifetime of the campaign. Would be useful in the Date and Time Range filter to have a button to click for 'the length of the campaign', so that the dashboard just plotted the data since the campaign hashtag came into use. Not a big issue, but def a nice to have :)

**Comment by ElJocho** [comment]
Hey Pete,

Nice to hear about examples where our dashboard is used :)!

Would it be sufficient for your use case to have a button that "zooms" to the available data on the plotly graph? Then you could select the rough time where you think the campaign started (or if you just need monthly aggregation "entire duration") up until now, and just use the button to get a better graph. This change could be done quite easily and would only require small changes in the frontend.

![image](https://github.com/user-attachments/assets/391f4a62-aaf6-403d-b598-fa007d1d51cc)

A "only retrieve stats for the timeframe since the campaign started" button would require additional requests and changes to the backend, which could currently be too much work "just" for a quality of life change

**Comment by pedrito1414** [comment]
Hey Jochen, this would be great! I screenshot the graphs a lot and this is the real need.... Thanks

**Comment by ElJocho** [comment]
![Group 2(1)](https://github.com/user-attachments/assets/2a9b8578-a2ff-4fbd-a7fb-c76a0f97f470)

Good news! You can now use the buttons that can be seen in the screenshot above to zoom to the content, and back out again. The buttons appear when hovering with the mouse over the plot.

Let us know if that resolves this issue for you, hope this feature will serve you well :)

**Comment by pedrito1414** [comment]
I love it... Thanks @ElJocho! Hope you're well!
